### ISSUE TITLE
概率性出现这样的问题

### ISSUE THREAD

**Issue by pengjunhong** [kingofglory/EasyPay#10]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tjl.super_warehouse/com.tjl.super_warehouse.wxapi.WXPayEntryActivity}: java.lang.NullPointerException: NullPointerException in DoInvoke because of null receiver
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
    at android.os.Handler.dispatchMessage(Handler.java:112)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.NullPointerException: NullPointerException in DoInvoke because of null receiver
    at com.tjl.super_warehouse.wxapi.WXPayEntryActivity.onCreate(WXPayEntryActivity.java)
    at android.app.Activity.performCreate(Activity.java:7458)
    at android.app.Activity.performCreate(Activity.java:7448)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
    ... 11 more

**Comment by kingofglory** [comment]
com.tjl.super_warehouse.wxapi.WXPayEntryActivity.onCreate  这个类是你自己的类吗？这看上去跟我这个框架不相关。而且我这边已经不需要提供wxapi.WXPayEntryActivity的了，只需要配置一个applicationId
